### ISSUE TITLE
Wikipedia data file no longer exists

### ISSUE THREAD

**Issue by gnewton** [blevesearch/bleve-bench#14]
http://people.apache.org/~gsingers/wikipedia/enwiki-20070527-pages-articles.xml.bz2 now returns a 404. It appears to not be in that user's directories (I looked in ~gsingers & the 'wikipedia' directory is also not there...).

Perhaps https://dumps.wikimedia.org/enwiki/20170301/enwiki-20170301-pages-articles.xml.bz2 could be used (~13GB) but I am guessing this is much larger than the 2007 version...?

There are no dumps older than 20161020 at https://dumps.wikimedia.org/enwiki/

**Comment by mschoch** [comment]
Thanks for reporting this.  I have a copy of the file, let me see if I can host it somewhere.  I'd rather not change files as our historical benchmark data relies on it.

**Comment by gnewton** [comment]
OK, sounds good!  :-)

**Comment by mschoch** [comment]
OK, new location: http://snapshots.couchbase.com.s3.amazonaws.com/bleve-bench/enwiki-20070527-pages-articles.xml.bz2

Do you know where you saw the link to the old location?

**Comment by mschoch** [comment]
I found a reference in the Makefile and updated it here: https://github.com/blevesearch/bleve-bench/commit/863e034dc0592d816a46d4094dd9213673eee697

If you know of anywhere else let me know.

**Comment by gnewton** [comment]
Yes, it was the one in the Makefile I was referring to.

Looks good to me. Thanks!  :-)
